# Generated by Django 4.1.3 on 2022-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_room_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
